Pandas is one of the most important python libraries for data analysis, data cleaning, data manipulation.

In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

- 1 D datastructure (Series)
- 2 D datastructure (DataFrame)

<h2>Data Frame</h2>

In [3]:
data = {
    "Name":["Rahul","Krish","Mohit"],
    "Course":["Math","React","Java"],
    "Age":[23,24,25]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

    Name Course  Age
0  Rahul   Math   23
1  Krish  React   24
2  Mohit   Java   25

In [8]:
type(df)

pandas.DataFrame

<h2>Series</h2>

In [6]:
s = pd.Series([34,54,23])

In [7]:
s

0    34
1    54
2    23
dtype: int64

In [9]:
type(s)

pandas.Series

<h2>Sample Dataset</h2>

In [13]:
df = pd.DataFrame({
    "Name":["Amit","Riya","John","Sara","Amit","Sneha"],
    "Age":[22,25,30,None,20,31],
    "Salary":[50000,60000,70000,65000,50000,63000],
    "City":["Delhi","Mumbai","Delhi","Pune","Delhi","Pune"]
})

In [14]:
df

    Name   Age  Salary    City
0   Amit  22.0   50000   Delhi
1   Riya  25.0   60000  Mumbai
2   John  30.0   70000   Delhi
3   Sara   NaN   65000    Pune
4   Amit  20.0   50000   Delhi
5  Sneha  31.0   63000    Pune

To Show top rows (head())

In [21]:
df.head(2)

   Name   Age  Salary    City
0  Amit  22.0   50000   Delhi
1  Riya  25.0   60000  Mumbai

To show bottom rows (tail())

In [28]:
df.tail(3)

    Name   Age  Salary   City
3   Sara   NaN   65000   Pune
4   Amit  20.0   50000  Delhi
5  Sneha  31.0   63000   Pune

In [ ]:
df.shape #(rows,columns)

(6, 4)

In [29]:
df.columns

Index(['Name', 'Age', 'Salary', 'City'], dtype='str')

In [30]:
df.describe()

             Age        Salary
count   5.000000      6.000000
mean   25.600000  59666.666667
std     4.827007   8164.965809
min    20.000000  50000.000000
25%    22.000000  52500.000000
50%    25.000000  61500.000000
75%    30.000000  64500.000000
max    31.000000  70000.000000

In [31]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     5 non-null      float64
 2   Salary  6 non-null      int64
 3   City    6 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 324.0 bytes

In [33]:
df.dtypes

Name          str
Age       float64
Salary      int64
City          str
dtype: object

In [34]:
import numpy as np

In [112]:
df = pd.DataFrame({
    "Name":["Amit","Riya","John","Sara","Amit","Sneha"],
    "Age":[22,25,30,None,20,31],
    "Salary":[50000,60000,None,65000,None,63000],
    "City":["Delhi",np.nan,"Delhi","Pune","Delhi",None]
})

In [36]:
df

    Name   Age   Salary   City
0   Amit  22.0  50000.0  Delhi
1   Riya  25.0  60000.0    NaN
2   John  30.0      NaN  Delhi
3   Sara   NaN  65000.0   Pune
4   Amit  20.0      NaN  Delhi
5  Sneha  31.0  63000.0    NaN

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     5 non-null      float64
 2   Salary  4 non-null      float64
 3   City    4 non-null      str
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

In [114]:
df

    Name   Age   Salary   City
0   Amit  22.0  50000.0  Delhi
1   Riya  25.0  60000.0    NaN
2   John  30.0      NaN  Delhi
3   Sara   NaN  65000.0   Pune
4   Amit  20.0      NaN  Delhi
5  Sneha  31.0  63000.0    NaN

In [ ]:
df.isnull()

    Name    Age  Salary   City
0  False  False   False  False
1  False  False   False   True
2  False  False    True  False
3  False   True   False  False
4  False  False    True  False
5  False  False   False   True

In [115]:
df.isnull().sum()

Name      0
Age       1
Salary    2
City      2
dtype: int64

In [116]:
len(df)

6

In [ ]:
df.isnull().sum()/len(df)

Name      0.000000
Age       0.166667
Salary    0.333333
City      0.333333
dtype: float64

In [44]:
len(df)

6

In [119]:
df.isnull().sum()/len(df)*100

Name       0.000000
Age       16.666667
Salary    33.333333
City      33.333333
dtype: float64

In [52]:
df["Salary_spike"] = df['Salary']*0.1

In [53]:
df

    Name   Age   Salary   City  Salary_spike
0   Amit  22.0  50000.0  Delhi        5000.0
1   Riya  25.0  60000.0    NaN        6000.0
2   John  30.0      NaN  Delhi           NaN
3   Sara   NaN  65000.0   Pune        6500.0
4   Amit  20.0      NaN  Delhi           NaN
5  Sneha  31.0  63000.0    NaN        6300.0

In [58]:
df['Salary_spike_filled'] = df['Salary_spike'].fillna(2000)

In [59]:
df

    Name   Age   Salary   City  Salary_spike  Salary_spike_filled
0   Amit  22.0  50000.0  Delhi        5000.0               5000.0
1   Riya  25.0  60000.0    NaN        6000.0               6000.0
2   John  30.0      NaN  Delhi           NaN               2000.0
3   Sara   NaN  65000.0   Pune        6500.0               6500.0
4   Amit  20.0      NaN  Delhi           NaN               2000.0
5  Sneha  31.0  63000.0    NaN        6300.0               6300.0

In [60]:
df['City'] = df['City'].fillna("Unknown")

In [61]:
df

    Name   Age   Salary     City  Salary_spike  Salary_spike_filled
0   Amit  22.0  50000.0    Delhi        5000.0               5000.0
1   Riya  25.0  60000.0  Unknown        6000.0               6000.0
2   John  30.0      NaN    Delhi           NaN               2000.0
3   Sara   NaN  65000.0     Pune        6500.0               6500.0
4   Amit  20.0      NaN    Delhi           NaN               2000.0
5  Sneha  31.0  63000.0  Unknown        6300.0               6300.0

In [62]:
df['Salary'].mean()

np.float64(59500.0)

In [63]:
df['Salary_filled'] = df['Salary'].fillna(df['Salary'].mean())

In [64]:
df

,Name,Age,Salary,City,Salary_spike,Salary_spike_filled,Salary_filled
0,Amit,22.0,50000.0,Delhi,5000.0,5000.0,50000.0
1,Riya,25.0,60000.0,Unknown,6000.0,6000.0,60000.0
2,John,30.0,NaN,Delhi,NaN,2000.0,59500.0
3,Sara,NaN,65000.0,Pune,6500.0,6500.0,65000.0
4,Amit,20.0,NaN,Delhi,NaN,2000.0,59500.0
5,Sneha,31.0,63000.0,Unknown,6300.0,6300.0,63000.0

In [80]:
df = pd.DataFrame({
    "Name":["Amit","Riya","John","Sara","Amit","Sneha"],
    "Age":[22,25,30,None,20,31],
    "Salary":[50000,60000,None,65000,None,63000],
    "City":["Delhi",np.nan,"Delhi","Pune","Delhi",None]
})

In [66]:
df

    Name   Age   Salary   City
0   Amit  22.0  50000.0  Delhi
1   Riya  25.0  60000.0    NaN
2   John  30.0      NaN  Delhi
3   Sara   NaN  65000.0   Pune
4   Amit  20.0      NaN  Delhi
5  Sneha  31.0  63000.0    NaN

In [78]:
df.dropna(inplace=True)

In [79]:
df

   Name   Age   Income   City
0  Amit  22.0  50000.0  Delhi

In [67]:
df_dropped = df.dropna()

In [68]:
df_dropped

   Name   Age   Salary   City
0  Amit  22.0  50000.0  Delhi

In [73]:
df_age_drop = df.dropna(subset=["Age","Salary"])
df_age_drop

    Name   Age   Salary   City
0   Amit  22.0  50000.0  Delhi
1   Riya  25.0  60000.0    NaN
5  Sneha  31.0  63000.0    NaN

In [81]:
df.rename(columns={"Salary":"Income"},inplace=True)

In [90]:
df

    Name   Age   Income   City
0   Amit    22  50000.0  Delhi
1   Riya    25  60000.0    NaN
2   John    30      NaN  Delhi
3   Sara  <NA>  65000.0   Pune
4   Amit    20      NaN  Delhi
5  Sneha    31  63000.0    NaN

In [87]:
df.dtypes

Name          str
Age         Int64
Income    float64
City          str
dtype: object

In [84]:
df['Age'] = df['Age'].astype('Int64')

In [91]:
df['City'].value_counts()

City
Delhi    3
Pune     1
Name: count, dtype: int64

In [94]:
df['City'].unique()

<StringArray>
['Delhi', nan, 'Pune']
Length: 3, dtype: str

In [107]:
df.sort_values("Age",ascending=False,inplace=True)

In [110]:
df.sort_index(inplace=True)

In [111]:
df

    Name   Age   Income   City
0   Amit    22  50000.0  Delhi
1   Riya    25  60000.0    NaN
2   John    30      NaN  Delhi
3   Sara  <NA>  65000.0   Pune
4   Amit    20      NaN  Delhi
5  Sneha    31  63000.0    NaN