<h1><strong>Indexing</strong></h1>

- Label based
- Position based

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "Name":["Amit","Riya","John","Sara","Amit","Sneha"],
    "Age":[22,25,30,None,20,31],
    "Salary":[50000,60000,None,65000,None,63000],
    "City":["Delhi",np.nan,"Delhi","Pune","Delhi",None]
},index=["a","b","c","d","e","f"])

In [8]:
df

    Name   Age   Salary   City
a   Amit  22.0  50000.0  Delhi
b   Riya  25.0  60000.0    NaN
c   John  30.0      NaN  Delhi
d   Sara   NaN  65000.0   Pune
e   Amit  20.0      NaN  Delhi
f  Sneha  31.0  63000.0    NaN

Label based indexing

In [16]:
df.loc['a':'d',["Name","Age","Salary"]]

   Name   Age   Salary
a  Amit  22.0  50000.0
b  Riya  25.0  60000.0
c  John  30.0      NaN
d  Sara   NaN  65000.0

In [ ]:
df.loc['a'].values

Position based Indexing

In [18]:
df.iloc[0:3,1:3]

    Age   Salary
a  22.0  50000.0
b  25.0  60000.0
c  30.0      NaN

In [22]:
df['Age']>25

a    False
b    False
c     True
d    False
e    False
f     True
Name: Age, dtype: bool

In [24]:
df[(df['Age']>20) & (df['City']=="Delhi")]

   Name   Age   Salary   City
a  Amit  22.0  50000.0  Delhi
c  John  30.0      NaN  Delhi

In [25]:
df.filter(items=['Name','Age'])

    Name   Age
a   Amit  22.0
b   Riya  25.0
c   John  30.0
d   Sara   NaN
e   Amit  20.0
f  Sneha  31.0

In [30]:
df.filter(like='A')

    Age
a  22.0
b  25.0
c  30.0
d   NaN
e  20.0
f  31.0

In [38]:
df.filter(items=['a',"c",'b','d'],axis=0)

   Name   Age   Salary   City
a  Amit  22.0  50000.0  Delhi
c  John  30.0      NaN  Delhi
b  Riya  25.0  60000.0    NaN
d  Sara   NaN  65000.0   Pune

In [47]:
df[["Age","Salary"]].query("Salary > 50000 or Age > 30")

    Age   Salary
b  25.0  60000.0
d   NaN  65000.0
f  31.0  63000.0

In [48]:
df.isnull().sum()

Name      0
Age       1
Salary    2
City      2
dtype: int64

In [49]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [50]:
df

    Name   Age   Salary   City
a   Amit  22.0  50000.0  Delhi
b   Riya  25.0  60000.0    NaN
c   John  30.0      NaN  Delhi
d   Sara  25.6  65000.0   Pune
e   Amit  20.0      NaN  Delhi
f  Sneha  31.0  63000.0    NaN

In [51]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

In [54]:
df['City'] = df['City'].fillna("Lucknow")

In [55]:
df.groupby("City")['Salary'].sum()

City
Delhi      169000.0
Lucknow    123000.0
Pune        65000.0
Name: Salary, dtype: float64

In [56]:
df.groupby('City')['Salary'].agg(['sum','mean','min','max'])

              sum          mean      min      max
City
Delhi    169000.0  56333.333333  50000.0  59500.0
Lucknow  123000.0  61500.000000  60000.0  63000.0
Pune      65000.0  65000.000000  65000.0  65000.0

In [57]:
df['Job_Role'] = ['IT','IT','Finance','Sales','Sales','IT']

In [58]:
df

    Name   Age   Salary     City Job_Role
a   Amit  22.0  50000.0    Delhi       IT
b   Riya  25.0  60000.0  Lucknow       IT
c   John  30.0  59500.0    Delhi  Finance
d   Sara  25.6  65000.0     Pune    Sales
e   Amit  20.0  59500.0    Delhi    Sales
f  Sneha  31.0  63000.0  Lucknow       IT

In [60]:
df.groupby(['Job_Role','City'])['Salary'].agg(['sum'])

                       sum
Job_Role City
Finance  Delhi     59500.0
IT       Delhi     50000.0
         Lucknow  123000.0
Sales    Delhi     59500.0
         Pune      65000.0

In [61]:
df.groupby('Job_Role').size()

Job_Role
Finance    1
IT         3
Sales      2
dtype: int64

In [64]:
df.pivot_table(values="Salary",index="City",aggfunc="sum",columns="Job_Role")

Job_Role  Finance        IT    Sales
City
Delhi     59500.0   50000.0  59500.0
Lucknow       NaN  123000.0      NaN
Pune          NaN       NaN  65000.0

In [72]:
df['City'] = df['City'].replace("Delhi","New Delhi")

In [73]:
df

    Name   Age   Salary       City Job_Role
a   Amit  22.0  50000.0  New Delhi       IT
b   Riya  25.0  60000.0    Lucknow       IT
c   John  30.0  59500.0  New Delhi  Finance
d   Sara  25.6  65000.0       Pune    Sales
e   Amit  20.0  59500.0  New Delhi    Sales
f  Sneha  31.0  63000.0    Lucknow       IT