<h2>What are missing values?</h2>

We encounter cells that are empty, null or undefined. These are called missing values - data point that were expected but were not recorded.

In python and pandas, missing values appear as NaN (not a number), None, or sometime as string like "N/A","-", or "unkown" that must be manually converted

<h2>Types of missing values</h2>

- MCAR - Missing completely at random
- MAR - Missing at random
- MNAR - Missing not at random

<h2>1. MCAR</h2>

The probability of a value being missed has absolutely no relationship with any variable in dataset.

<h2>2. MAR</h2>

The missingness is related to observed data, but not the missing values themselves.

<h2>3. MNAR</h2>

The missingness depends on the observed value itself. This is hardest to handle.

<h2>Methods for handling missing values</h2>

1. Removing missing values(Deletion Technique)
    
    1.1 Row Deletion(List wise deletion)<br>
    1.2 column Deletion(Drop features)<br>

2. Imputation
    
    2.1 Univariate Imputation<br>
    2.1.1 Numerical Value Imputation<br>
    2.1.2 Categorical. value Imputation<br>

    2.2 Multivariate Imputation<br>
    2.2.1 KNN-Imputer<br>
    2.2.2 Iterative Imputer<br>

In [1]:
import pandas as pd
import numpy as np

data = {
    'Name':["Rohan","Krish","Bob","Sohit","Kashish","Mayank"],
    'Age':[24,np.nan,34,23,np.nan,40],
    'Score':[85,90,np.nan,88,92,95],
    "Attendance":[100,90,80,np.nan,90,85]
}

df = pd.DataFrame(data)

In [7]:
df.isnull().mean()*100

Name           0.000000
Age           33.333333
Score         16.666667
Attendance    16.666667
dtype: float64

<h2>Row deletion</h2>

<h3>When it is good to use?</h3>

- Low percentage: if < 5% data is missing
- MCAR: The missingness has no hidden pattern
- Large Dataset: If you have 1 million rows losing 1000 wont hurt your model's performance.


<h3>When not to use it?</h3>

- Small dataset: if you only have 100 rows, every single rows is precious
- Bias risk: If only "High Income" individuals refused to answer the sruvey, dropping those rows remove "high income" representation entirely

In [9]:
df_dropped = df.dropna()

In [11]:
df

      Name   Age  Score  Attendance
0    Rohan  24.0   85.0       100.0
1    Krish   NaN   90.0        90.0
2      Bob  34.0    NaN        80.0
3    Sohit  23.0   88.0         NaN
4  Kashish   NaN   92.0        90.0
5   Mayank  40.0   95.0        85.0

In [10]:
df_dropped

     Name   Age  Score  Attendance
0   Rohan  24.0   85.0       100.0
5  Mayank  40.0   95.0        85.0

In [12]:
df_subset = df.dropna(subset=['Score','Attendance'])

In [14]:
df

      Name   Age  Score  Attendance
0    Rohan  24.0   85.0       100.0
1    Krish   NaN   90.0        90.0
2      Bob  34.0    NaN        80.0
3    Sohit  23.0   88.0         NaN
4  Kashish   NaN   92.0        90.0
5   Mayank  40.0   95.0        85.0

In [13]:
df_subset

      Name   Age  Score  Attendance
0    Rohan  24.0   85.0       100.0
1    Krish   NaN   90.0        90.0
4  Kashish   NaN   92.0        90.0
5   Mayank  40.0   95.0        85.0

In [25]:
dt = pd.DataFrame({
    "A":[1,np.nan,3,np.nan],
    "B":[4,None,np.nan,np.nan],
    "C":[7,8,9,np.nan]
})

In [26]:
dt

     A    B    C
0  1.0  4.0  7.0
1  NaN  NaN  8.0
2  3.0  NaN  9.0
3  NaN  NaN  NaN

In [27]:
dt.dropna(thresh=1)

     A    B    C
0  1.0  4.0  7.0
1  NaN  NaN  8.0
2  3.0  NaN  9.0

<h2>Column Deletion</h2>

<h3>When it is good to Use</h3>

- High missingness: eg > 50,60 ,70...
- Irrelevance: If the feature is not crucial for the prediction

<h3>When it is not recommended</h3>

- Domain importance

In [28]:
df['Notes'] = [np.nan,"Good",np.nan,np.nan,np.nan,"Average"]

In [29]:
df

      Name   Age  Score  Attendance    Notes
0    Rohan  24.0   85.0       100.0      NaN
1    Krish   NaN   90.0        90.0     Good
2      Bob  34.0    NaN        80.0      NaN
3    Sohit  23.0   88.0         NaN      NaN
4  Kashish   NaN   92.0        90.0      NaN
5   Mayank  40.0   95.0        85.0  Average

In [42]:
missing_percentage = df.isnull().sum()/len(df)*100

In [43]:
missing_percentage.index

Index(['Name', 'Age', 'Score', 'Attendance', 'Notes'], dtype='str')

In [55]:
missing_percentage.values

array([ 0.        , 33.33333333, 16.66666667, 16.66666667, 66.66666667])

In [54]:
limit = 30

columns_to_drop = missing_percentage[missing_percentage>limit].index

columns_to_drop

Index(['Age', 'Notes'], dtype='str')

In [47]:
df_reduced = df.drop(columns=columns_to_drop)

In [48]:
df_reduced

      Name  Score  Attendance
0    Rohan   85.0       100.0
1    Krish   90.0        90.0
2      Bob    NaN        80.0
3    Sohit   88.0         NaN
4  Kashish   92.0        90.0
5   Mayank   95.0        85.0