<h1><strong>Encoding Categorical Data</strong></h1>

In [15]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 100

df = pd.DataFrame(
    {
        "age":np.random.randint(18,60,n),
        "salary":np.random.randint(30000,100000,n),
        "city":np.random.choice(["Delhi","Mumbai","Pune","Noida"],n),
        "gender":np.random.choice(["Male","Female"],n),
        "education":np.random.choice(['High School','Graduate','Post Graduate'],n)
    }
)

In [3]:
df.head()

   age  salary    city  gender      education
0   56   38392  Mumbai  Female       Graduate
1   46   60535  Mumbai    Male  Post Graduate
2   32   82256    Pune    Male  Post Graduate
3   25   65222    Pune  Female       Graduate
4   38   93335   Noida    Male  Post Graduate

<h2>Label Encoder</h2>

Label encoder assign unique number to each category.

In [ ]:
pip install scikit-learn

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['City_label'] = le.fit_transform(df['city'])

In [7]:
df.head(10)

   age  salary    city  gender      education  City_label
0   56   38392  Mumbai  Female       Graduate           1
1   46   60535  Mumbai    Male  Post Graduate           1
2   32   82256    Pune    Male  Post Graduate           3
3   25   65222    Pune  Female       Graduate           3
4   38   93335   Noida    Male  Post Graduate           2
5   56   40965   Noida  Female    High School           2
6   36   54538  Mumbai    Male       Graduate           1
7   40   38110   Noida  Female  Post Graduate           2
8   28   57266   Delhi    Male       Graduate           0
9   28   82992   Noida  Female    High School           2

<h2>One Hot Encoder</h2>

Gives you sparse matrix(0,1) and generate columns to each category.

In [17]:
from sklearn.preprocessing import OneHotEncoder

oe = OneHotEncoder()

encoded = oe.fit_transform(df[['city']]).toarray()

In [18]:
df[["Delhi","Mumbai","Noida","Pune"]] = encoded

In [20]:
df.head(10)

,age,salary,city,gender,education,City_label,Delhi,Mumbai,Noida,Pune
0,56,38392,Mumbai,Female,Graduate,1,0.0,1.0,0.0,0.0
1,46,60535,Mumbai,Male,Post Graduate,1,0.0,1.0,0.0,0.0
2,32,82256,Pune,Male,Post Graduate,3,0.0,0.0,0.0,1.0
3,25,65222,Pune,Female,Graduate,3,0.0,0.0,0.0,1.0
4,38,93335,Noida,Male,Post Graduate,2,0.0,0.0,1.0,0.0
5,56,40965,Noida,Female,High School,2,0.0,0.0,1.0,0.0
6,36,54538,Mumbai,Male,Graduate,1,0.0,1.0,0.0,0.0
7,40,38110,Noida,Female,Post Graduate,2,0.0,0.0,1.0,0.0
8,28,57266,Delhi,Male,Graduate,0,1.0,0.0,0.0,0.0
9,28,82992,Noida,Female,High School,2,0.0,0.0,1.0,0.0

<h2>Ordinal Encoder </h2>

Used when categories have order

In [21]:
from sklearn.preprocessing import OrdinalEncoder

categories = [["High School","Graduate","Post Graduate"]]

oe = OrdinalEncoder(categories=categories)

df['education_encoded'] = oe.fit_transform(df[['education']])

In [22]:
df.head(10)

,age,salary,city,gender,education,City_label,Delhi,Mumbai,Noida,Pune,education_encoded
0,56,38392,Mumbai,Female,Graduate,1,0.0,1.0,0.0,0.0,1.0
1,46,60535,Mumbai,Male,Post Graduate,1,0.0,1.0,0.0,0.0,2.0
2,32,82256,Pune,Male,Post Graduate,3,0.0,0.0,0.0,1.0,2.0
3,25,65222,Pune,Female,Graduate,3,0.0,0.0,0.0,1.0,1.0
4,38,93335,Noida,Male,Post Graduate,2,0.0,0.0,1.0,0.0,2.0
5,56,40965,Noida,Female,High School,2,0.0,0.0,1.0,0.0,0.0
6,36,54538,Mumbai,Male,Graduate,1,0.0,1.0,0.0,0.0,1.0
7,40,38110,Noida,Female,Post Graduate,2,0.0,0.0,1.0,0.0,2.0
8,28,57266,Delhi,Male,Graduate,0,1.0,0.0,0.0,0.0,1.0
9,28,82992,Noida,Female,High School,2,0.0,0.0,1.0,0.0,0.0